[package]
name = "grafana-proxy-microsoft_power_automate"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
serde_json = "1"
clap = { version = "4.5", features = ["derive"] }
